title: NiftyBlocks Wiki
author: Shmeggels

description: > # this means to ignore newlines until "twitter_username:"
NiftyBlocks is a creative and survival-friendly mod that adds in various materials, lawn flamingos, the nifty block, and much much more!  You can craft a rainbow of dyed versions of wooden planks and bricks with the addition of NiftyBlocks' own sets of blocks like checkered tiles, lamps, vinyl siding and, stucco. Light up your land with the lovely wooden lamps or the colored glow lamps. Hungry? fear not because NiftyBlocks adds in 28 different foods including pizza, various fruits, doughnuts, bacon, baked beans, and other foodstuffs which can be found in your world. NiftyBlocks is an excellent addition to your game if you are a modern map maker since it adds in 72 different traffic signs, asphalt in black grey yellow, and white colors, traffic lights, traffic cones, and safety poles for your modern Minecraft city. The sky's the limit with NiftyBlocks! 

# social links
twitter_username: jekyllrb
github_username:  mariofish
rss: rss
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
